import {Droplets, Moon, Star, Sunrise, Thermometer, Waves} from "lucide-react"

export const onsenExperiences = [
    {
        id: 1,
        name: "Sunrise Onsen",
        description: "Begin your day with a rejuvenating soak as the first light touches the mountain peaks",
        temperature: "40-42°C",
        capacity: "6 guests",
        duration: "60 minutes",
        price: 65,
        rating: 4.9,
        category: "Morning",
        icon: Sunrise,
        imageUrl: "/placeholder.svg?height=400&width=600&text=Dark+sunrise+mountain+hot+springs",
        features: ["Mountain sunrise views", "Natural mineral water", "Private changing rooms", "Herbal tea service"],
        benefits: ["Improved circulation", "Stress relief", "Muscle relaxation", "Mental clarity"],
        schedule: ["6:00 AM", "6:30 AM", "7:00 AM"],
    },
    {
        id: 2,
        name: "Moonlight Onsen",
        description: "Soak under the stars in our most serene hot spring experience with celestial views",
        temperature: "38-40°C",
        capacity: "4 guests",
        duration: "90 minutes",
        price: 85,
        rating: 4.9,
        category: "Evening",
        icon: Moon,
        imageUrl: "/placeholder.svg?height=400&width=600&text=Dark+moonlit+hot+springs+with+stars",
        features: ["Stargazing views", "Cooler temperature", "Extended soaking time", "Night meditation"],
        benefits: ["Deep relaxation", "Better sleep", "Stress reduction", "Spiritual connection"],
        schedule: ["8:00 PM", "9:30 PM"],
    },
    {
        id: 3,
        name: "Forest Onsen",
        description: "Immerse yourself in nature with our secluded hot spring surrounded by ancient pines",
        temperature: "41-43°C",
        capacity: "8 guests",
        duration: "75 minutes",
        price: 75,
        rating: 4.8,
        category: "Nature",
        icon: Droplets,
        imageUrl: "/placeholder.svg?height=400&width=600&text=Dark+forest+hot+springs+surrounded+by+trees",
        features: ["Forest setting", "Natural sounds", "Higher mineral content", "Aromatherapy from pines"],
        benefits: ["Detoxification", "Skin health", "Respiratory wellness", "Nature connection"],
        schedule: ["10:00 AM", "2:00 PM", "4:00 PM"],
    },
    {
        id: 4,
        name: "Private Onsen Suite",
        description: "Exclusive hot spring experience for couples or small groups seeking ultimate privacy",
        temperature: "39-42°C",
        capacity: "2-3 guests",
        duration: "120 minutes",
        price: 150,
        rating: 4.9,
        category: "Private",
        icon: Star,
        imageUrl: "/placeholder.svg?height=400&width=600&text=Dark+private+luxury+hot+springs+suite",
        features: ["Complete privacy", "Personal attendant", "Premium amenities", "Champagne service"],
        benefits: ["Intimate experience", "Personalized service", "Ultimate relaxation", "Romantic setting"],
        schedule: ["By appointment"],
    },
]

export const onsenBenefits = [
    {
        title: "Mineral Healing",
        description: "Our natural hot springs contain sulfur, calcium, and magnesium for therapeutic benefits",
        icon: Thermometer,
    },
    {
        title: "Stress Relief",
        description: "The warm mineral water naturally reduces cortisol levels and promotes deep relaxation",
        icon: Waves,
    },
    {
        title: "Improved Circulation",
        description: "Heat therapy dilates blood vessels, improving circulation and reducing muscle tension",
        icon: Droplets,
    },
    {
        title: "Better Sleep",
        description: "Regular onsen bathing helps regulate body temperature for deeper, more restful sleep",
        icon: Moon,
    },
]