import {Coffee, Dumbbell, Flower, Heart, Mountain, Sparkles, Sun, TreePine, Utensils, Waves} from "lucide-react";

export const amenities = [
    {
        id: 1,
        name: "Meditation Gardens",
        description: "Tranquil outdoor spaces designed for mindfulness and reflection under ancient mountain pines",
        icon: Flower,
        category: "Wellness",
        imageUrl: "/placeholder.svg?height=300&width=400&text=Dark zen garden with stone paths and meditation areas",
        features: ["Guided meditation sessions", "Peaceful water features", "Aromatherapy plants", "Quiet zones"],
    },
    {
        id: 2,
        name: "Mountain Hot Springs",
        description: "Natural thermal waters sourced from deep mountain springs for ultimate relaxation",
        icon: Waves,
        category: "Wellness",
        imageUrl: "/placeholder.svg?height=300&width=400&text=Dark mountain hot springs with steam and rocks",
        features: ["Natural mineral waters", "Private onsen", "Stargazing pools", "Therapeutic treatments"],
    },
    {
        id: 3,
        name: "Wellness Studio",
        description: "Modern fitness facilities with yoga classes and personal training in mountain serenity",
        icon: Dumbbell,
        category: "Fitness",
        imageUrl: "/placeholder.svg?height=300&width=400&text=Dark modern wellness studio with mountain views",
        features: ["Daily yoga classes", "Personal training", "Meditation workshops", "Fitness equipment"],
    },
    {
        id: 4,
        name: "Infinity Pool",
        description: "Stunning infinity pool overlooking the mountain valleys with heated comfort year-round",
        icon: Mountain,
        category: "Recreation",
        imageUrl: "/placeholder.svg?height=300&width=400&text=Dark infinity pool with mountain valley views",
        features: ["Heated pool", "Pool bar service", "Lounge chairs", "Sunset views"],
    },
    {
        id: 5,
        name: "Mountain Cuisine",
        description: "Farm-to-table restaurant focusing on seasonal, organic mountain cuisine",
        icon: Utensils,
        category: "Dining",
        imageUrl: "/placeholder.svg?height=300&width=400&text=Dark elegant mountain restaurant with warm lighting",
        features: ["Organic ingredients", "Seasonal menus", "Wine pairings", "Private dining"],
    },
    {
        id: 6,
        name: "Forest Trails",
        description: "Scenic walking paths through ancient forests and meadows with guided nature experiences",
        icon: TreePine,
        category: "Recreation",
        imageUrl: "/placeholder.svg?height=300&width=400&text=Dark forest trail with dappled sunlight",
        features: ["Guided nature walks", "Bird watching", "Photography spots", "Picnic areas"],
    },
    {
        id: 7,
        name: "Sunrise Deck",
        description: "Elevated platform perfect for morning meditation and yoga with panoramic mountain views",
        icon: Sun,
        category: "Wellness",
        imageUrl: "/placeholder.svg?height=300&width=400&text=Dark wooden deck with sunrise mountain views",
        features: ["Morning yoga", "Sunrise viewing", "Meditation space", "Tea service"],
    },
    {
        id: 8,
        name: "Wellness Library",
        description: "Quiet reading space with books on mindfulness, nature, and personal growth",
        icon: Coffee,
        category: "Relaxation",
        imageUrl: "/placeholder.svg?height=300&width=400&text=Dark cozy library with fireplace and mountain views",
        features: ["Wellness books", "Quiet atmosphere", "Comfortable seating", "Tea and coffee"],
    },
    {
        id: 9,
        name: "Spa Sanctuary",
        description: "Full-service spa offering rejuvenating treatments inspired by mountain healing traditions",
        icon: Heart,
        category: "Wellness",
        imageUrl: "/placeholder.svg?height=300&width=400&text=Dark luxurious spa treatment room with candles",
        features: ["Massage therapy", "Facial treatments", "Aromatherapy", "Couples treatments"],
    },
    {
        id: 10,
        name: "Stargazing Observatory",
        description: "High-altitude observatory for celestial viewing and astronomical meditation",
        icon: Sparkles,
        category: "Recreation",
        imageUrl: "/placeholder.svg?height=300&width=400&text=Dark observatory dome with night sky and stars",
        features: ["Telescope access", "Guided stargazing", "Astronomy talks", "Night photography"],
    },
]