import {Coffee, Leaf, Utensils, Wine} from "lucide-react";

export const diningExperiences = [
    {
        id: 1,
        name: "Kaiseki Tasting Menu",
        description: "Traditional multi-course meal celebrating seasonal mountain ingredients with artistic presentation",
        category: "Fine Dining",
        duration: "2.5 hours",
        capacity: "12 guests",
        price: 185,
        rating: 4.9,
        icon: Utensils,
        imageUrl: "/kaiseki.jpg",
        features: ["9-course tasting", "Seasonal ingredients", "Wine pairings", "Private dining"],
        schedule: ["6:00 PM", "8:30 PM"],
        philosophy:
            "Each dish tells the story of the mountain's seasonal gifts, prepared with reverence for nature's bounty.",
    },
    {
        id: 2,
        name: "Mountain Tea Ceremony",
        description: "Authentic tea ceremony experience in our traditional tea house overlooking the zen garden",
        category: "Cultural",
        duration: "90 minutes",
        capacity: "6 guests",
        price: 75,
        rating: 4.8,
        icon: Coffee,
        imageUrl: "/mountain_tea.jpg",
        features: ["Premium teas", "Traditional sweets", "Cultural education", "Garden views"],
        schedule: ["10:00 AM", "2:00 PM", "4:00 PM"],
        philosophy: "The way of tea teaches us to find beauty in simplicity and presence in each mindful moment.",
    },
    {
        id: 3,
        name: "Sake & Mountain Views",
        description: "Curated sake tasting featuring local breweries paired with mountain-inspired small plates",
        category: "Tasting",
        duration: "2 hours",
        capacity: "8 guests",
        price: 125,
        rating: 4.7,
        icon: Wine,
        imageUrl: "/mount_sake.jpg",
        features: ["5 premium sakes", "Local breweries", "Artisan plates", "Sunset timing"],
        schedule: ["5:00 PM", "7:00 PM"],
        philosophy: "Like the mountains themselves, great sake is shaped by time, patience, and respect for tradition.",
    },
    {
        id: 4,
        name: "Forest Foraging Breakfast",
        description: "Early morning foraging expedition followed by a farm-to-table breakfast featuring your discoveries",
        category: "Adventure",
        duration: "3 hours",
        capacity: "10 guests",
        price: 95,
        rating: 4.6,
        icon: Leaf,
        imageUrl: "/forest_breakfast.jpg",
        features: ["Guided foraging", "Wild ingredients", "Cooking class", "Mountain breakfast"],
        schedule: ["6:30 AM"],
        philosophy: "Connect with the mountain's natural abundance and learn the ancient art of living from the land.",
    },
]

export const menuHighlights = [
    {
        name: "Mountain Mist Soup",
        description: "Delicate mushroom broth with foraged herbs and mountain vegetables",
        price: 28,
        category: "Appetizer",
    },
    {
        name: "Cedar-Smoked Trout",
        description: "Local trout smoked over mountain cedar with seasonal root vegetables",
        price: 42,
        category: "Main Course",
    },
    {
        name: "Zen Garden Salad",
        description: "Organic greens with edible flowers and house-made sesame dressing",
        price: 24,
        category: "Salad",
    },
    {
        name: "Moonlight Mochi",
        description: "House-made mochi with seasonal fruit and mountain honey",
        price: 18,
        category: "Dessert",
    },
]